### ISSUE TITLE
Bootstrap Modal not working when RTE add media hook is used.

### ISSUE THREAD

**Issue by altoin** [Strategy11/formidable-modal#9] opened 2020-09-15 09:59 UTC
When this hook https://formidableforms.com/knowledgebase/frm_rte_options/#kb-add-media-button-to-tinymce-editor is used to add a media button to a RichText field, the bootstrap modal doesn't on any page where the Form with the RTE is added.

**Comment by Crabcyborg** [comment] 2023-11-08 15:01
I just tested this. I can confirm this was a bug in v2.0 but is since fixed in v3.0.1 🚀.

**Closed by Crabcyborg** 2023-11-08 15:01 UTC
Labels: type: enhancement
